"""
Core AGI System Components

This module provides the foundational components for building AGI-capable agents:
- BaseAgent: Core agent with EXPLORE/VERIFY/PLAN/EXECUTE/REFLECT cycle
- MemoryManager: Hierarchical memory (working, episodic, semantic)
- Planner: Task decomposition and parallel execution planning
- ReflectionEngine: Self-correction and learning from execution
"""

from .agent import BaseAgent, AgentState, Thought, Action, ExecutionResult
from .memory import MemoryManager, MemoryEntry
from .planner import Planner, PlanNode, ExecutionPlan
from .reflection import ReflectionEngine, ReflectionResult
from .evidence_ledger import (
    Claim,
    ClaimStatus,
    ClaimVerification,
    Evidence,
    EvidenceKind,
    EvidenceLedger,
    EvidencePolarity,
    LedgerSummary,
    create_ledger,
)
from .trace_grounding import (
    StepGrounding,
    TraceGrounder,
    TraceGroundingReport,
    ground_trace,
)
from .recursive_self_improvement import (
    BRAKE_VISIBILITY,
    BrakePedal,
    BrakeState,
    EvidenceRequirement,
    EvidenceStatus,
    ProposalStatus,
    RSIController,
    RSIControllerConfig,
    RSIDecision,
    RSIProposal,
    RecursionDepthBudget,
    RecursionDepthExceeded,
    RiskBand,
    SELF_SURFACE_PREFIXES,
    classify_risk,
    make_rsi_id,
    metacognitive_adjust,
    proposal_from_improvement_proposal,
)
from .three_ring_architecture import (
    AgentDescriptor,
    CapabilityTailwind,
    CostClass,
    FederationLayer,
    FrontierLayer,
    PermissionScope,
    RingLayer,
    RiskProfile,
    R2_DEFAULT_PERMISSIONS,
    R3_DEFAULT_PERMISSIONS,
    RING_TO_RISK,
    RoutingDecision,
    StrategyPlan,
    ThreeRingGovernor,
    create_three_ring_governor,
    make_ring2_agent,
    make_ring3_agent,
)
from .proof_carrying_action import (
    ActionCertificate,
    AdmissibilityDecision,
    AdmissibilityVerdict,
    ApprovalReceipt,
    CertificateState,
    Checkpoint,
    CheckpointKind,
    DataClassification,
    EnforceabilityClass,
    ExternalityContext,
    ExternalityPolicy,
    IEECStep,
    ProofCarryingActionBridge,
    ReversalBound,
    canonical_hash,
    create_pca_bridge,
    digest_certificate,
)
from .governed_action_loop import (
    ACTION_TYPE_TO_CATEGORY,
    CrossCheckOutcome,
    CrossCheckReport,
    GovernedActionLoop,
    GovernedActionRequest,
    RISK_TO_ENFORCEABILITY,
    create_governed_loop,
)
from .tool_privilege_governor import (
    CandidateRanking,
    InsufficiencyReport,
    SelectionOutcome,
    SelectionRecord,
    StepRequest,
    ToolPrivilegeDescriptor,
    ToolPrivilegeGovernor,
    ToolPrivilegeGovernorConfig,
    create_tool_privilege_governor,
    make_high_privilege_tool,
    make_low_privilege_tool,
)
from .memory_refiner import (
    RefinementAction,
    RefinementCandidatePair,
    RefinementDecision,
    RefinementJudge,
    RefinementReport,
    MemoryRefinerConfig,
    MemoryRefiner,
    FactDensityJudge,
    LLMJudgeStub,
    create_memory_refiner,
)

from .agent_loop import (
    AgentIdentity,
    AgentLoop,
    AgentLoopConfig,
    BreakerGateVerifier,
    BudgetStatus,
    CompositeVerifier,
    LedgerGateVerifier,
    LifecycleState,
    LoopBudget,
    LoopStep,
    MonitorGateVerifier,
    Permission,
    RevocationChannel,
    StepPhase,
    Verdict,
    VerifierProtocol,
    create_agent_loop,
    strongest,
)

from .cef_detector import (
    CEFAction,
    CEFDetection,
    CEFDetector,
    CEFDetectorConfig,
    CEFMarker,
    CEFPattern,
    CEFSeverity,
    CEFType,
    create_cef_detector,
    detect_cef,
)

__all__ = [
    "BaseAgent",
    "AgentState",
    "Thought",
    "Action",
    "ExecutionResult",
    "MemoryManager",
    "MemoryEntry",
    "Planner",
    "PlanNode",
    "ExecutionPlan",
    "ReflectionEngine",
    "ReflectionResult",
    "Claim",
    "ClaimStatus",
    "ClaimVerification",
    "Evidence",
    "EvidenceKind",
    "EvidenceLedger",
    "EvidencePolarity",
    "LedgerSummary",
    "create_ledger",
    "StepGrounding",
    "TraceGrounder",
    "TraceGroundingReport",
    "ground_trace",
    "BrakePedal",
    "BrakeState",
    "EvidenceRequirement",
    "EvidenceStatus",
    "ProposalStatus",
    "RSIController",
    "RSIControllerConfig",
    "RSIDecision",
    "RSIProposal",
    "RecursionDepthBudget",
    "RecursionDepthExceeded",
    "RiskBand",
    "SELF_SURFACE_PREFIXES",
    "BRAKE_VISIBILITY",
    "classify_risk",
    "make_rsi_id",
    "metacognitive_adjust",
    "proposal_from_improvement_proposal",
    "AgentDescriptor",
    "CapabilityTailwind",
    "CostClass",
    "FederationLayer",
    "FrontierLayer",
    "PermissionScope",
    "RingLayer",
    "RiskProfile",
    "R2_DEFAULT_PERMISSIONS",
    "R3_DEFAULT_PERMISSIONS",
    "RING_TO_RISK",
    "RoutingDecision",
    "StrategyPlan",
    "ThreeRingGovernor",
    "create_three_ring_governor",
    "make_ring2_agent",
    "make_ring3_agent",
    # Proof-Carrying Action bridge (PCAA + SARC + OpenKedge + PCE)
    "ActionCertificate",
    "AdmissibilityDecision",
    "AdmissibilityVerdict",
    "ApprovalReceipt",
    "CertificateState",
    "Checkpoint",
    "CheckpointKind",
    "DataClassification",
    "EnforceabilityClass",
    "ExternalityContext",
    "ExternalityPolicy",
    "IEECStep",
    "ProofCarryingActionBridge",
    "ReversalBound",
    "canonical_hash",
    "create_pca_bridge",
    "digest_certificate",
    # Governed Action Loop (PCA + Breaker + Ledger + Three-Ring bridge)
    "ACTION_TYPE_TO_CATEGORY",
    "RISK_TO_ENFORCEABILITY",
    "CrossCheckOutcome",
    "CrossCheckReport",
    "GovernedActionLoop",
    "GovernedActionRequest",
    "create_governed_loop",
    # Tool Privilege Governor (ToolPrivBench + CAPSPLIT-IB + RACG-inspired)
    "CandidateRanking",
    "InsufficiencyReport",
    "SelectionOutcome",
    "SelectionRecord",
    "StepRequest",
    "ToolPrivilegeDescriptor",
    "ToolPrivilegeGovernor",
    "ToolPrivilegeGovernorConfig",
    "create_tool_privilege_governor",
    "make_high_privilege_tool",
    "make_low_privilege_tool",
    # Memory Refiner (MemRefine-inspired compression/refinement layer)
    "FactDensityJudge",
    "LLMJudgeStub",
    "MemoryRefiner",
    "MemoryRefinerConfig",
    "RefinementAction",
    "RefinementCandidatePair",
    "RefinementDecision",
    "RefinementJudge",
    "RefinementReport",
    "create_memory_refiner",
    # CEF / CET Detector (arXiv:2606.14831)
    "CEFAction",
    "CEFDetection",
    "CEFDetector",
    "CEFDetectorConfig",
    "CEFMarker",
    "CEFPattern",
    "CEFSeverity",
    "CEFType",
    "create_cef_detector",
    "detect_cef",
]  # type: ignore[has-type]  # keep flake8 quiet on trailing-comma list

from .cef_session import (
    CEFSessionAction,
    CEFSessionConfig,
    CEFSessionDetector,
    CEFSessionState,
    CEFSessionVerdict,
    create_cef_session_detector,
    detect_cef_session,
)
from .cef_substrate_integration import (
    CEFBreakerOutcome,
    CEFBreakerVerdict,
    CEFIntegrationConfig,
    CEFLedgerOutcome,
    CEFLoopStep,
    assess_cef_to_breaker,
    create_cef_integration,
    fold_step_into_cef,
    record_cef_to_ledger,
)
from .cef_probabilistic_verification import (
    DEFAULT_BAND_THRESHOLDS,
    BetaPosterior,
    ProbabilisticTripEngine,
    TripBand,
    TripObservation,
    band_for_upper_bound,
    create_probabilistic_trip_engine,
    dro_bernoulli_upper_bound,
)